// 利用規約・プライバシーポリシーの本文。LoginModal（登録時の同意）と
// LegalModal（いつでも閲覧できるモーダル）で共有する。
// 現在は日本語・英語のみ提供（他言語は将来の多言語再公開時に ja へフォールバックする）。
import { Language } from './i18n/translations';

export interface LegalSection {
  title: string;
  body?: string;
  list?: string[];
  contact?: boolean;
}

export const TERMS_LAST_UPDATED: Record<'ja' | 'en', string> = {
  ja: '2026年7月22日',
  en: 'July 22, 2026',
};
export const PRIVACY_LAST_UPDATED: Record<'ja' | 'en', string> = {
  ja: '2026年7月22日',
  en: 'July 22, 2026',
};

export const CONTACT_EMAIL = 'do.man.26.shibaura@gmail.com';

const TERMS_SECTIONS_JA: LegalSection[] = [
  { title: '第1条（目的）', body: '本サービス「世界のひとさじ」（以下「本サービス」）は、世界各国の調味料に関する情報をユーザーが投稿・共有し、閲覧・検索できるプラットフォームです。ユーザーは本規約に同意の上、本サービスを利用するものとします。' },
  { title: '第2条（投稿コンテンツ）', body: 'ユーザーは、文章、画像、動画、レビューその他の情報（以下「投稿コンテンツ」）を投稿できます。投稿者は、投稿コンテンツについて必要な権利を有し、または適法な利用許諾を得ていることを保証するものとします。' },
  { title: '第3条（禁止事項）', list: ['他者の著作権、商標権、肖像権、プライバシー権その他の権利を侵害する行為', 'メーカー公式サイト、ECサイト、カタログ、雑誌等から無断転載した画像の投稿', '虚偽または誤解を招く情報の投稿', '誹謗中傷、差別的表現、嫌がらせ行為', '法令または公序良俗に反する行為', 'スパム投稿、広告投稿、営利目的の不正利用', 'システムへの不正アクセス', 'その他、運営者が不適切と判断する行為'] },
  { title: '第4条（投稿コンテンツの利用許諾）', body: 'ユーザーは、投稿コンテンツについて著作権を保持します。ただしユーザーは運営者に対し、本サービスの運営・改善・広報・研究開発・マーケティング分析を目的として、投稿コンテンツを無償かつ非独占的に利用、複製、編集、公開、翻訳できる権利を許諾するものとします。' },
  { title: '第5条（AI生成コンテンツ）', body: 'AI技術により生成された画像または文章を投稿する場合、ユーザーは可能な限りその旨を明示するものとします。AI生成コンテンツについても第三者の権利を侵害しないことを保証するものとします。' },
  { title: '第6条（コンテンツの削除）', body: '運営者は規約違反、権利侵害申告、法令上の要請があった場合、事前通知なく投稿コンテンツを削除または非公開にすることができます。' },
  { title: '第7条（個人情報の取り扱い）', body: 'ユーザー登録時に取得する氏名・生年月日・性別・居住地は、統計分析・サービス改善・本人確認の目的にのみ利用し、第三者に開示しません。詳細はプライバシーポリシーをご確認ください。ニックネームおよび味覚バッジは、投稿とともに他のユーザーに公開されます。' },
  { title: '第8条（著作権ポリシー）', body: '投稿者は自身が権利を有するコンテンツのみを投稿してください。他サイトからの無断転載、雑誌・書籍のスキャン画像、他者が撮影した画像の無断使用は禁止します。権利侵害を発見した場合は下記窓口へご連絡ください。', contact: true },
  { title: '第9条（免責事項）', body: '掲載情報はユーザー投稿を含みます。原材料、栄養成分、アレルギー情報等については必ずメーカー公式情報をご確認ください。本サービスの情報に基づいて生じた損害について、運営者は責任を負いません。' },
  { title: '第10条（規約の変更）', body: '運営者は必要に応じて本規約を変更できるものとします。変更後の規約は本サービス上に掲示した時点で効力を生じ、以後のご利用には変更後の規約が適用されます。' },
  { title: '第11条（準拠法・管轄）', body: '本規約は日本法に準拠します。本サービスに関して紛争が生じた場合、運営者所在地を管轄する裁判所を第一審の専属的合意管轄裁判所とします。' },
];

const TERMS_SECTIONS_EN: LegalSection[] = [
  { title: 'Article 1 (Purpose)', body: 'This service, "A Spoonful of the World" (the "Service"), is a platform where users can post, share, browse, and search information about condiments from around the world. By using the Service, users agree to these Terms of Use.' },
  { title: 'Article 2 (User Content)', body: 'Users may post text, images, videos, reviews, and other information ("Posted Content"). Users warrant that they hold the necessary rights to any Posted Content or have obtained lawful permission to use it.' },
  { title: 'Article 3 (Prohibited Conduct)', list: ['Infringing on the copyrights, trademarks, portrait rights, privacy rights, or other rights of others', 'Posting images copied without authorization from manufacturers\' official sites, e-commerce sites, catalogs, or magazines', 'Posting false or misleading information', 'Defamation, discriminatory expression, or harassment', 'Acts that violate laws or public order and morals', 'Spam, advertising posts, or unauthorized use for commercial purposes', 'Unauthorized access to the system', 'Any other conduct the operator deems inappropriate'] },
  { title: 'Article 4 (License to Posted Content)', body: 'Users retain copyright in their Posted Content. However, users grant the operator a free, non-exclusive license to use, reproduce, edit, publish, and translate Posted Content for the purpose of operating, improving, promoting, researching, and analyzing the Service.' },
  { title: 'Article 5 (AI-Generated Content)', body: 'When posting images or text generated by AI technology, users shall indicate this whenever reasonably possible. Users also warrant that AI-generated content does not infringe on the rights of third parties.' },
  { title: 'Article 6 (Removal of Content)', body: 'The operator may remove or unpublish Posted Content without prior notice in the event of a violation of these Terms, a rights infringement claim, or a legal requirement.' },
  { title: 'Article 7 (Handling of Personal Information)', body: 'The full name, date of birth, gender, and place of residence collected during registration are used solely for statistical analysis, service improvement, and identity verification, and are not disclosed to third parties. Please refer to the Privacy Policy for details. Nicknames and taste badges are made public to other users alongside posts.' },
  { title: 'Article 8 (Copyright Policy)', body: 'Users may only post content they have the right to post. Unauthorized reposting from other sites, scanned images from magazines or books, and unauthorized use of images taken by others are prohibited. If you discover a rights infringement, please contact us at the address below.', contact: true },
  { title: 'Article 9 (Disclaimer)', body: 'Listed information includes user-submitted content. Please always check the manufacturer\'s official information regarding ingredients, nutritional content, allergen information, and the like. The operator is not liable for any damages arising from information on the Service.' },
  { title: 'Article 10 (Changes to These Terms)', body: 'The operator may revise these Terms as needed. Revised Terms take effect once posted on the Service, and subsequent use of the Service is governed by the revised Terms.' },
  { title: 'Article 11 (Governing Law and Jurisdiction)', body: 'These Terms are governed by the laws of Japan. Any disputes arising in connection with the Service shall be subject to the exclusive jurisdiction of the court having jurisdiction over the operator\'s location as the court of first instance.' },
];

const PRIVACY_SECTIONS_JA: LegalSection[] = [
  { title: '1. 事業者情報', body: '本サービス「世界のひとさじ」（以下「本サービス」）は、道満調味料研究所（以下「運営者」）が運営します。個人情報の取り扱いに関するお問い合わせは下記窓口までご連絡ください。', contact: true },
  { title: '2. 取得する情報', list: ['ユーザー登録時に入力される情報（氏名、ニックネーム、メールアドレス、生年月日、性別、居住地、味覚バッジ）', '投稿された調味料情報・レビュー・コメント・画像', 'いいね・ブックマークなどの操作履歴', 'サービス改善のための検索キーワード等の利用状況'] },
  { title: '3. 利用目的', list: ['本サービスの提供・運営・本人確認', '投稿・レビュー等のコンテンツ表示', 'ユーザーへの重要なお知らせや連絡', '統計分析によるサービスの改善・開発', '利用規約に違反する行為への対応'] },
  { title: '4. 公開範囲', body: 'ニックネーム、味覚バッジ、投稿内容（調味料情報・レビュー・画像等）は、本サービス上で他のユーザーに公開されます。氏名・生年月日・性別・居住地・メールアドレスは公開されず、運営者（管理者）のみが管理目的で確認します。' },
  { title: '5. 第三者提供', body: '運営者は、法令に基づく場合、または人の生命・身体・財産の保護に必要な場合を除き、あらかじめユーザーの同意を得ずに個人情報を第三者に提供しません。' },
  { title: '6. 外部サービスの利用', body: '本サービスは、認証・データ保存に Supabase、地図表示に OpenStreetMap、お問い合わせ通知メールの送信に EmailJS を利用しています。これらのサービスにおける情報の取り扱いは、各サービスのプライバシーポリシーに従います。' },
  { title: '7. 個人情報の管理', body: '運営者は、取得した個人情報の漏洩・滅失・毀損を防止するため、アクセス制御等の適切な安全管理措置を講じます。閲覧範囲は必要最小限の管理者に限定されます。' },
  { title: '8. 開示・訂正・削除', body: 'ユーザーは、自己の個人情報について開示・訂正・削除・利用停止を求めることができます。ご希望の場合は下記窓口までご連絡ください。なお、一部の情報（氏名・生年月日）は登録後に変更できない場合があります。' },
  { title: '9. Cookie等の利用', body: '本サービスは、ログイン状態の保持等のために、ブラウザのローカルストレージ・Cookie等を利用します。これらはユーザーを個人として特定する目的では利用しません。' },
  { title: '10. 改定', body: '本ポリシーは、法令の変更やサービス内容の変更に応じて改定されることがあります。改定後のポリシーは本サービス上に掲示した時点で効力を生じます。' },
];

const PRIVACY_SECTIONS_EN: LegalSection[] = [
  { title: '1. Operator Information', body: 'This service, "A Spoonful of the World" (the "Service"), is operated by Doman Seasoning Research Institute (the "Operator"). For inquiries regarding the handling of personal information, please contact us at the address below.', contact: true },
  { title: '2. Information We Collect', list: ['Information entered during user registration (full name, nickname, email address, date of birth, gender, place of residence, taste badges)', 'Posted condiment information, reviews, comments, and images', 'Activity history such as likes and bookmarks', 'Usage data such as search keywords, for service improvement'] },
  { title: '3. Purpose of Use', list: ['Providing, operating, and verifying the identity of users of the Service', 'Displaying content such as posts and reviews', 'Sending important notices and communications to users', 'Improving and developing the Service through statistical analysis', 'Responding to conduct that violates the Terms of Use'] },
  { title: '4. Scope of Disclosure', body: 'Nicknames, taste badges, and posted content (condiment information, reviews, images, etc.) are made public to other users on the Service. Full name, date of birth, gender, place of residence, and email address are not made public and are viewable only by the operator (administrator) for management purposes.' },
  { title: '5. Provision to Third Parties', body: 'The operator will not provide personal information to third parties without the user\'s prior consent, except where required by law or necessary to protect a person\'s life, body, or property.' },
  { title: '6. Use of External Services', body: 'This Service uses Supabase for authentication and data storage, OpenStreetMap for map display, and EmailJS for sending inquiry notification emails. The handling of information by these services is governed by each service\'s own privacy policy.' },
  { title: '7. Management of Personal Information', body: 'The operator takes appropriate security measures, such as access controls, to prevent the leakage, loss, or damage of collected personal information. Access is limited to the minimum number of administrators necessary.' },
  { title: '8. Disclosure, Correction, and Deletion', body: 'Users may request the disclosure, correction, deletion, or suspension of use of their own personal information. Please contact us at the address below if you wish to make such a request. Note that some information (full name, date of birth) may not be changeable after registration.' },
  { title: '9. Use of Cookies, etc.', body: 'This Service uses browser local storage, cookies, and similar technologies to, among other things, maintain login state. These are not used to personally identify users.' },
  { title: '10. Revisions', body: 'This Policy may be revised in response to changes in law or changes to the Service. Revised policies take effect once posted on the Service.' },
];

const TERMS_SECTIONS_BY_LANG: Record<'ja' | 'en', LegalSection[]> = {
  ja: TERMS_SECTIONS_JA,
  en: TERMS_SECTIONS_EN,
};
const PRIVACY_SECTIONS_BY_LANG: Record<'ja' | 'en', LegalSection[]> = {
  ja: PRIVACY_SECTIONS_JA,
  en: PRIVACY_SECTIONS_EN,
};

// 日本語のセクションを既定値としてエクスポート（後方互換用）
export const TERMS_SECTIONS = TERMS_SECTIONS_JA;
export const PRIVACY_SECTIONS = PRIVACY_SECTIONS_JA;

// 英語以外（未対応言語）は日本語にフォールバックする
export function getTermsSections(language: Language): LegalSection[] {
  return TERMS_SECTIONS_BY_LANG[language === 'en' ? 'en' : 'ja'];
}
export function getPrivacySections(language: Language): LegalSection[] {
  return PRIVACY_SECTIONS_BY_LANG[language === 'en' ? 'en' : 'ja'];
}
